.section luaAssets, "a"
.incbin "framework/core/Assets.lua"

.section luaClass, "a"
.incbin "framework/core/Class.lua"

.section luaDisplayImage, "a"
.incbin "framework/core/DisplayImage.lua"

.section luaDisplayNinepatch, "a"
.incbin "framework/core/DisplayNinepatch.lua"

.section luaDisplayObject, "a"
.incbin "framework/core/DisplayObject.lua"

.section luaDisplayPager, "a"
.incbin "framework/core/DisplayPager.lua"

.section luaDisplayScroll, "a"
.incbin "framework/core/DisplayScroll.lua"

.section luaDisplayText, "a"
.incbin "framework/core/DisplayText.lua"

.section luaEventDispatcher, "a"
.incbin "framework/core/EventDispatcher.lua"

.section luaI18n, "a"
.incbin "framework/core/I18n.lua"

.section luaPrintr, "a"
.incbin "framework/core/Printr.lua"

.section luaStage, "a"
.incbin "framework/core/Stage.lua"

.section luaTimer, "a"
.incbin "framework/core/Timer.lua"
